FROM golang:1.14-alpine

RUN apk add --no-cache bash \
                       build-base \
                       bzr \
                       curl \
                       docker-cli \
                       git \
                       mercurial \
                       build-base

ENTRYPOINT ["/entrypoint.sh"]
CMD [ "-h" ]

COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY goreleaser /bin/goreleaser
