FROM dockercore/golang-cross:1.13.12

RUN apt-get update && \
    apt-get install -y bash \
                       build-essential \
                       curl \
                       docker \
                       git \
                       mercurial \
                       rpm

ENTRYPOINT ["/entrypoint.sh"]
CMD [ "-h" ]

COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY goreleaser /bin/goreleaser
