GoReleaser: {
  Publish: {
    announce: 'Announce release' {
      Discord: {shape: step}
      LinkedIn: {shape: step}
      Mastodon: {shape: step}
      Mattermost: {shape: step}
      Reddit: {shape: step}
      Slack: {shape: step}
      SMTP: {shape: step}
      Teams: {shape: step}
      Telegram: {shape: step}
      Twitter: {shape: step}
      Webhook: {shape: step}

#      Discord -> LinkedIn -> Mastodon -> Mattermost -> Reddit -> Slack -> SMTP -> Teams -> Telegram -> Twitter -> Webhook
    }
  }
}
