#!/bin/bash
cat << 'INNER_EOF' > new_template.txt
const ebuildTemplate = `# This file was generated by GoReleaser. DO NOT EDIT.
EAPI=8

{{- if .Systemd }}
inherit systemd
{{- end }}

DESCRIPTION="{{ .Description }}"
HOMEPAGE="{{ .Homepage }}"
SRC_URI="
{{- range .Archs }}
  {{ .Keyword }}? ( {{ .URI }} -> {{ .File }} )
{{- end }}
"

LICENSE="{{ .License }}"
SLOT="0"
KEYWORDS="{{ .Keywords }}"
IUSE="doc{{ range .UseFlags }} {{ .Flag }}{{ end }}"

S="${WORKDIR}"

{{- define "use_start" }}
{{- if . }}
  if {{ range $i, $u := . }}{{ if $i }} && {{ end }}{{ if eq (slice $u 0 1) "!" }}! use {{ slice $u 1 }}{{ else }}use {{ $u }}{{ end }}{{ end }}; then
{{- end }}
{{- end }}

{{- define "use_end" }}
{{- if . }}
  fi
{{- end }}
{{- end }}

src_install() {
{{- with .ExtraInstall }}
  {{ . }}
{{- end }}
{{- with .Bindir }}
  exeinto {{ . }}
{{- end }}
{{- range .InstallGroups }}
{{- if and .Keywords (gt (len $.InstallGroups) 1) }}
  if {{ range $i, $k := .Keywords }}{{ if $i }} || {{ end }}use {{ $k }}{{ end }}; then
{{- range .Installs }}
    {{- if eq .Source .Target }}
    doexe "{{ .Source }}" || die "Failed to install binary"
    {{- else }}
    newexe "{{ .Source }}" "{{ .Target }}" || die "Failed to install binary"
    {{- end }}
{{- end }}
  fi
{{- else }}
{{- range .Installs }}
  {{- if eq .Source .Target }}
  doexe "{{ .Source }}" || die "Failed to install binary"
  {{- else }}
  newexe "{{ .Source }}" "{{ .Target }}" || die "Failed to install binary"
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range .Dobin }}
{{- template "use_start" .Use }}
{{- if .Target }}
  newbin "{{ .Source }}" "{{ .Base }}"
{{- else }}
  dobin "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Doconfd }}
{{- template "use_start" .Use }}
{{- if .Target }}
  newconfd "{{ .Source }}" "{{ .Base }}"
{{- else }}
  doconfd "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Dodir }}
  dodir "{{ . }}"
{{- end }}
{{- range .Doenvd }}
{{- template "use_start" .Use }}
{{- if .Target }}
  newenvd "{{ .Source }}" "{{ .Base }}"
{{- else }}
  doenvd "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Doexe }}
{{- template "use_start" .Use }}
{{- if .Target }}
  newexe "{{ .Source }}" "{{ .Base }}"
{{- else }}
  doexe "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Doheader }}
{{- template "use_start" .Use }}
{{- if .Target }}
  newheader "{{ .Source }}" "{{ .Base }}"
{{- else }}
  doheader "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Doinitd }}
{{- template "use_start" .Use }}
{{- if .Target }}
  newinitd "{{ .Source }}" "{{ .Base }}"
{{- else }}
  doinitd "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Doins }}
{{- template "use_start" .Use }}
{{- if .Target }}
  insinto "{{ .Dir }}"
  newins "{{ .Source }}" "{{ .Base }}"
{{- else }}
  insinto /
  doins "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Dosbin }}
{{- template "use_start" .Use }}
{{- if .Target }}
  newsbin "{{ .Source }}" "{{ .Base }}"
{{- else }}
  dosbin "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Dosym }}
{{- template "use_start" .Use }}
  dosym "{{ .Source }}" "{{ .Target }}"
{{- template "use_end" .Use }}
{{- end }}
{{- range .Systemd }}
{{- template "use_start" .Use }}
{{- if .Target }}
  systemd_newunit "{{ .Source }}" "{{ .Base }}"
{{- else }}
  systemd_dounit "{{ .Source }}"
{{- end }}
{{- template "use_end" .Use }}
{{- end }}
{{- range .Doman }}
  doman "{{ . }}"
{{- end }}
{{- range .Dodoc }}
  dodoc "{{ . }}"
{{- end }}
  if use doc; then
    dodoc README* || die
  fi
}
`
INNER_EOF
awk '
BEGIN { in_template = 0 }
/^const ebuildTemplate = / { in_template = 1; while (getline line < "new_template.txt") print line; next }
/^`$/ { if (in_template) { in_template = 0; next } }
{ if (!in_template) print }
' internal/pipe/gentoo/gentoo.go > internal/pipe/gentoo/gentoo.go.new
mv internal/pipe/gentoo/gentoo.go.new internal/pipe/gentoo/gentoo.go
