# This file was generated by GoReleaser. DO NOT EDIT.
cask "{{ .Name }}" do
  desc "{{ .Description }}"
  homepage "{{ .Homepage }}"
  version "{{ .Version }}"
  {{- with .License }}
  license "{{ .}}"
  {{- end }}

  livecheck do
    skip "Auto-generated on release."
  end

  {{ with .Binary }}
  binary "{{ .}}"
  {{- end }}
  {{- with .Manpage }}
  manpage "{{ .}}"
  {{- end }}
  {{- with .Completions.Bash }}
  bash_completions "{{ . }}"
  {{- end }}
  {{- with .Completions.Zsh }}
  zsh_completions "{{ . }}"
  {{- end }}
  {{- with .Completions.Fish }}
  fish_completions "{{ . }}"
  {{- end }}

  {{- with .Dependencies }}
  {{ range  . }}
  {{- with .Cask }}
  depends_on cask: "{{ . }}"
  {{- end }}
  {{- with .Formula }}
  depends_on formula: "{{ . }}"
  {{- end }}
  {{- end }}
  {{- end }}

  {{ if .MacOSPackages }}
  on_macos do
  {{- include "macos_packages" . | indent 2 }}
  end
  {{ end }}

  {{ if .LinuxPackages }}
  on_linux do
  {{- include "linux_packages" . | indent 2 }}
  end
  {{ end }}

  {{- with .Conflicts }}
  {{ range . }}
  {{- with .Cask }}
  conflicts_with cask: "{{ . }}"
  {{- end }}
  {{- with .Formula }}
  conflicts_with formula: "{{ . }}"
  {{- end }}
  {{- end }}
  {{- end }}

  {{ with .CustomBlock -}}
  {{ range (split .) }}
  {{ . }}
  {{- end }}
  {{- end }}

  {{ with .Hooks.Pre.Install -}}
  preflight do
    {{- range (split .) }}
    {{ . }}
    {{- end }}
  end
  {{- end }}

  {{ with .Hooks.Post.Install -}}
  postflight do
    {{- range (split .) }}
    {{ . }}
    {{- end }}
  end
  {{- end }}

  {{ with .Hooks.Pre.Uninstall -}}
  uninstall_preflight do
    {{- range (split .) }}
    {{ . }}
    {{- end }}
  end
  {{- end }}

  {{ with .Hooks.Post.Uninstall -}}
  uninstall_postflight do
    {{- range (split .) }}
    {{ . }}
    {{- end }}
  end
  {{- end }}

  {{ with .Caveats -}}
  caveats do
    {{- range (split .) }}
    "{{ . -}}"
    {{- end }}
  end
  {{- end }}

  {{ with .Service -}}
  service "{{ . }}"
  {{- end }}


  {{ if .Uninstall.HasAny -}}

  {{ with .Uninstall.Launchctl -}}
  uninstall launchctl: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Uninstall.Quit -}}
  uninstall quit: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Uninstall.LoginItem -}}
  uninstall login_item: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Uninstall.Trash -}}
  uninstall trash: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Uninstall.Delete -}}
  uninstall delete: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}
  {{- end }}

  {{ if .Zap.HasAny -}}

  {{ with .Zap.Launchctl -}}
  zap launchctl: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Zap.Quit -}}
  zap quit: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Zap.LoginItem -}}
  zap login_item: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Zap.Trash -}}
  zap trash: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ with .Zap.Delete -}}
  zap delete: [
    {{- range . }}
    "{{ . }}",
    {{- end }}
  ]
  {{- end }}

  {{ else }}
  # No zap stanza required
  {{- end }}
end
