# This script was generated by goreleaser.com. DO NOT EDIT.
# {{ .GeneratedBy }}

[CmdletBinding()]
param(
  [string]$InstallTo = "{{ .DefaultInstallWindows }}",
  [string]$Version = "{{ .DefaultTag }}"
)

if ([string]::IsNullOrWhiteSpace($Version)) {
  $Version = "{{ .DefaultVersion }}"
}

$Tag = if ($Version.StartsWith("v")) { $Version } else { "v$Version" }
$RuntimeArch = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()
$Arch = switch ($RuntimeArch) {
  "x64" { "amd64" }
  "arm64" { "arm64" }
  "x86" { "386" }
  default { throw "unsupported architecture: $RuntimeArch" }
}
$OS = "windows"

function Get-Asset {
  param([string]$Os, [string]$Arch)
  # Prefer OS-specific universal assets (goarch=all) first.
  {{- range .Assets }}
  {{- if eq .Arch "all" }}
  if ($Os -eq "{{ .OS }}") {
    return [pscustomobject]@{
      Kind = "{{ .Kind }}"
      Format = "{{ .Format }}"
      NamePattern = "{{ .NamePattern }}"
      UrlPattern = "{{ .URLPattern }}"
      BinaryPath = "{{ .BinaryPath }}"
      InstallName = "{{ .InstallName }}"
    }
  }
  {{- end }}
  {{- end }}

  # Then try exact architecture matches.
  {{- range .Assets }}
  {{- if ne .Arch "all" }}
  if ($Os -eq "{{ .OS }}" -and $Arch -eq "{{ .Arch }}") {
    return [pscustomobject]@{
      Kind = "{{ .Kind }}"
      Format = "{{ .Format }}"
      NamePattern = "{{ .NamePattern }}"
      UrlPattern = "{{ .URLPattern }}"
      BinaryPath = "{{ .BinaryPath }}"
      InstallName = "{{ .InstallName }}"
    }
  }
  {{- end }}
  {{- end }}
  throw "no installable asset found for $Os/$Arch"
}

$asset = Get-Asset -Os $OS -Arch $Arch
$assetName = $asset.NamePattern.Replace("__GORELEASER_TAG__", $Tag).Replace("__GORELEASER_VERSION__", $Version)
$assetUrl = $asset.UrlPattern.Replace("__GORELEASER_TAG__", $Tag).Replace("__GORELEASER_VERSION__", $Version)

{{- if .MessageBefore }}
Write-Host "{{ .MessageBefore }}"
{{- end }}

$tmpDir = New-Item -ItemType Directory -Path (Join-Path $env:TEMP ("goreleaser-install-" + [guid]::NewGuid().ToString("N")))
try {
  $downloadPath = Join-Path $tmpDir.FullName $assetName
  Invoke-WebRequest -Uri $assetUrl -OutFile $downloadPath

  if ($asset.Kind -eq "binary") {
    $binPath = $downloadPath
  } else {
    $extractDir = Join-Path $tmpDir.FullName "extracted"
    Expand-Archive -Path $downloadPath -DestinationPath $extractDir -Force
    $candidate = Join-Path $extractDir $asset.BinaryPath
    if (Test-Path $candidate) {
      $binPath = $candidate
    } else {
      $binPath = Get-ChildItem -Path $extractDir -File -Recurse |
        Where-Object { $_.Name -ieq [System.IO.Path]::GetFileName($asset.BinaryPath) } |
        Select-Object -First 1 -ExpandProperty FullName
    }
  }

  if (-not $binPath -or -not (Test-Path $binPath)) {
    throw "could not find binary in downloaded asset"
  }

  $resolvedInstallTo = [Environment]::ExpandEnvironmentVariables($InstallTo)
  if ($resolvedInstallTo.StartsWith("~")) {
    $resolvedInstallTo = Join-Path $HOME $resolvedInstallTo.Substring(1).TrimStart('\', '/')
  }
  New-Item -ItemType Directory -Path $resolvedInstallTo -Force | Out-Null

  $target = Join-Path $resolvedInstallTo $asset.InstallName
  Copy-Item -Path $binPath -Destination $target -Force
  Write-Host "installed $($asset.InstallName) to $resolvedInstallTo"
} finally {
  Remove-Item -Path $tmpDir.FullName -Recurse -Force -ErrorAction SilentlyContinue
}

{{- if .MessageAfter }}
Write-Host "{{ .MessageAfter }}"
{{- end }}
