#!/bin/sh
set -eu

# This script was generated by goreleaser.com. DO NOT EDIT.
# {{ .GeneratedBy }}

INSTALL_TO=""
VERSION="{{ .DefaultTag }}"

usage() {
  cat <<'EOF'
Usage: install.sh [--install-to DIR] [--version VERSION]
  --install-to DIR  Directory to install the binary to
  --version VERSION Release version/tag to install
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --install-to)
      INSTALL_TO="${2-}"
      shift 2
      ;;
    --version)
      VERSION="${2-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$VERSION" ]; then
  VERSION="{{ .DefaultVersion }}"
fi

TAG="$VERSION"
case "$TAG" in
  v*) ;;
  *) TAG="v$TAG" ;;
esac

OS="$(uname -s)"
case "$OS" in
  Linux) OS="linux" ;;
  Darwin) OS="darwin" ;;
  *)
    echo "unsupported operating system: $OS" >&2
    exit 1
    ;;
esac

if [ -z "$INSTALL_TO" ]; then
  case "$OS" in
    linux) INSTALL_TO="{{ .DefaultInstallLinux }}" ;;
    darwin) INSTALL_TO="{{ .DefaultInstallDarwin }}" ;;
  esac
fi

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  i386|i686) ARCH="386" ;;
  armv7l|armv6l|arm) ARCH="arm" ;;
  *)
    echo "unsupported architecture: $ARCH" >&2
    exit 1
    ;;
esac

select_asset() {
  # Prefer OS-specific universal assets (goarch=all) first.
  {{- range .Assets }}
  {{- if eq .Arch "all" }}
  if [ "$OS" = "{{ .OS }}" ]; then
    ASSET_KIND="{{ .Kind }}"
    ASSET_FORMAT="{{ .Format }}"
    ASSET_NAME_PATTERN="{{ .NamePattern }}"
    ASSET_URL_PATTERN="{{ .URLPattern }}"
    ASSET_BINARY_PATH="{{ .BinaryPath }}"
    ASSET_INSTALL_NAME="{{ .InstallName }}"
    return 0
  fi
  {{- end }}
  {{- end }}

  # Then try exact architecture matches.
  {{- range .Assets }}
  {{- if ne .Arch "all" }}
  if [ "$OS" = "{{ .OS }}" ] && [ "$ARCH" = "{{ .Arch }}" ]; then
    ASSET_KIND="{{ .Kind }}"
    ASSET_FORMAT="{{ .Format }}"
    ASSET_NAME_PATTERN="{{ .NamePattern }}"
    ASSET_URL_PATTERN="{{ .URLPattern }}"
    ASSET_BINARY_PATH="{{ .BinaryPath }}"
    ASSET_INSTALL_NAME="{{ .InstallName }}"
    return 0
  fi
  {{- end }}
  {{- end }}
  return 1
}

if ! select_asset; then
  echo "no installable asset found for ${OS}/${ARCH}" >&2
  exit 1
fi

ASSET_NAME=$(printf "%s" "$ASSET_NAME_PATTERN" | sed "s|__GORELEASER_TAG__|$TAG|g; s|__GORELEASER_VERSION__|$VERSION|g")
ASSET_URL=$(printf "%s" "$ASSET_URL_PATTERN" | sed "s|__GORELEASER_TAG__|$TAG|g; s|__GORELEASER_VERSION__|$VERSION|g")

{{- if .MessageBefore }}
echo "{{ .MessageBefore }}"
{{- end }}

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT INT TERM
DOWNLOAD_PATH="$TMPDIR/$ASSET_NAME"

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required" >&2
  exit 1
fi
curl -fsSL "$ASSET_URL" -o "$DOWNLOAD_PATH"

if [ "$ASSET_KIND" = "binary" ]; then
  BIN_PATH="$DOWNLOAD_PATH"
else
  EXTRACTED="$TMPDIR/extracted"
  mkdir -p "$EXTRACTED"
  case "$ASSET_FORMAT" in
    zip)
      if ! command -v unzip >/dev/null 2>&1; then
        echo "unzip is required to extract $ASSET_NAME" >&2
        exit 1
      fi
      unzip -q "$DOWNLOAD_PATH" -d "$EXTRACTED"
      ;;
    *)
      tar -xf "$DOWNLOAD_PATH" -C "$EXTRACTED"
      ;;
  esac
  if [ -f "$EXTRACTED/$ASSET_BINARY_PATH" ]; then
    BIN_PATH="$EXTRACTED/$ASSET_BINARY_PATH"
  else
    BIN_PATH="$(find "$EXTRACTED" -type f -name "$(basename "$ASSET_BINARY_PATH")" | head -n 1)"
  fi
fi

if [ -z "${BIN_PATH:-}" ] || [ ! -f "$BIN_PATH" ]; then
  echo "could not find binary in downloaded asset" >&2
  exit 1
fi

INSTALL_TO="${INSTALL_TO/#\~/$HOME}"
mkdir -p "$INSTALL_TO"
chmod +x "$BIN_PATH"
cp "$BIN_PATH" "$INSTALL_TO/$ASSET_INSTALL_NAME"
chmod +x "$INSTALL_TO/$ASSET_INSTALL_NAME"
echo "installed $ASSET_INSTALL_NAME to $INSTALL_TO"

{{- if .MessageAfter }}
echo "{{ .MessageAfter }}"
{{- end }}
