package installscript

import (
	"bytes"
	"cmp"
	"embed"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	texttemplate "text/template"

	"github.com/caarlos0/log"
	"github.com/goreleaser/goreleaser/v2/internal/artifact"
	"github.com/goreleaser/goreleaser/v2/internal/client"
	"github.com/goreleaser/goreleaser/v2/internal/commitauthor"
	"github.com/goreleaser/goreleaser/v2/internal/pipe"
	"github.com/goreleaser/goreleaser/v2/internal/skips"
	"github.com/goreleaser/goreleaser/v2/internal/tmpl"
	"github.com/goreleaser/goreleaser/v2/pkg/config"
	"github.com/goreleaser/goreleaser/v2/pkg/context"
)

const (
	installScriptConfigExtra = "InstallScriptConfig"
	installScriptKindExtra   = "InstallScriptKind"
	installScriptPathExtra   = "InstallScriptPath"

	scriptKindUnix    = "unix"
	scriptKindWindows = "windows"

	installScriptIDUnix    = "install_script_unix"
	installScriptIDWindows = "install_script_windows"
	installScriptFileUnix  = "install.sh"
	installScriptFileWin   = "install.ps1"

	generatedMarker = "generated by goreleaser.com"

	patternTag     = "__GORELEASER_TAG__"
	patternVersion = "__GORELEASER_VERSION__"
)

//go:embed templates/*
var templates embed.FS

var (
	errNoRepoName                = pipe.Skip("install_script.repository.name is required")
	errNoScriptDirectory         = pipe.Skip("install_script.directory is required")
	errNoSuitableArtifact        = pipe.Skip("install_script: no suitable artifacts found")
	errGeneratedMarkerNotPresent = errors.New("install script does not include generated marker")
)

// Pipe for install_script generation and publishing.
type Pipe struct{}

func (Pipe) String() string        { return "install scripts" }
func (Pipe) ContinueOnError() bool { return true }
func (Pipe) Skip(ctx *context.Context) bool {
	if skips.Any(ctx, skips.InstallScript) {
		return true
	}
	cfg := ctx.Config.InstallScript
	return cfg.Repository.Name == "" && cfg.Repository.Git.URL == ""
}

func (Pipe) Default(ctx *context.Context) error {
	cfg := &ctx.Config.InstallScript
	if cfg.Repository.Name == "" && cfg.Repository.Git.URL == "" {
		return nil
	}
	cfg.CommitAuthor = commitauthor.Default(cfg.CommitAuthor)
	if cfg.CommitMessageTemplate == "" {
		cfg.CommitMessageTemplate = "Install script update for {{ .ProjectName }} version {{ .Tag }}"
	}
	if cfg.Directory == "" {
		cfg.Directory = "www/static"
	}
	if cfg.InstallTo.Linux == "" {
		cfg.InstallTo.Linux = "/usr/local/bin"
	}
	if cfg.InstallTo.Darwin == "" {
		cfg.InstallTo.Darwin = "/usr/local/bin"
	}
	if cfg.InstallTo.Windows == "" {
		cfg.InstallTo.Windows = "$env:ProgramFiles\\{{ .ProjectName }}"
	}
	if cfg.Goamd64 == "" {
		cfg.Goamd64 = "v1"
	}
	return nil
}

func (Pipe) Run(ctx *context.Context) error {
	cfg := ctx.Config.InstallScript
	if cfg.Repository.Name == "" && cfg.Repository.Git.URL == "" {
		return nil
	}

	enabled, err := tmpl.New(ctx).Bool(cfg.Enable)
	if err != nil {
		return err
	}
	if cfg.Enable != "" && !enabled {
		return pipe.Skip("install_script.enable evaluates to false")
	}
	if cfg.Directory == "" {
		return errNoScriptDirectory
	}

	tp := tmpl.New(ctx)
	if err := tp.ApplyAll(
		&cfg.Directory,
		&cfg.InstallTo.Linux,
		&cfg.InstallTo.Darwin,
		&cfg.InstallTo.Windows,
		&cfg.MessageBefore,
		&cfg.MessageAfter,
		&cfg.Enable,
		&cfg.URLTemplate,
	); err != nil {
		return err
	}

	ref, err := client.TemplateRef(tp.Apply, cfg.Repository)
	if err != nil {
		return err
	}
	cfg.Repository = ref
	if cfg.Repository.Name == "" && cfg.Repository.Git.URL == "" {
		return errNoRepoName
	}

	releaseClient, err := client.NewReleaseClient(ctx)
	if err != nil {
		return err
	}
	if cfg.URLTemplate == "" {
		cfg.URLTemplate, err = releaseClient.ReleaseURLTemplate(ctx)
		if err != nil {
			return err
		}
	}

	unixAssets, err := selectAssets(ctx, cfg, "linux", "darwin")
	if err != nil {
		return err
	}
	windowsAssets, err := selectAssets(ctx, cfg, "windows")
	if err != nil {
		return err
	}

	unixContent, err := renderScript("templates/install.sh", scriptTemplateData{
		ProjectName:          ctx.Config.ProjectName,
		DefaultTag:           ctx.Git.CurrentTag,
		DefaultVersion:       ctx.Version,
		DefaultInstallLinux:  cfg.InstallTo.Linux,
		DefaultInstallDarwin: cfg.InstallTo.Darwin,
		MessageBefore:        cfg.MessageBefore,
		MessageAfter:         cfg.MessageAfter,
		GeneratedBy:          generatedMarker,
		Assets:               unixAssets,
	})
	if err != nil {
		return err
	}
	windowsContent, err := renderScript("templates/install.ps1", scriptTemplateData{
		ProjectName:           ctx.Config.ProjectName,
		DefaultTag:            ctx.Git.CurrentTag,
		DefaultVersion:        ctx.Version,
		DefaultInstallWindows: cfg.InstallTo.Windows,
		MessageBefore:         cfg.MessageBefore,
		MessageAfter:          cfg.MessageAfter,
		GeneratedBy:           generatedMarker,
		Assets:                windowsAssets,
	})
	if err != nil {
		return err
	}

	unixTargetPath := filepath.ToSlash(filepath.Join(cfg.Directory, installScriptFileUnix))
	windowsTargetPath := filepath.ToSlash(filepath.Join(cfg.Directory, installScriptFileWin))

	unixOutPath := filepath.Join(ctx.Config.Dist, "install_script", installScriptFileUnix)
	windowsOutPath := filepath.Join(ctx.Config.Dist, "install_script", installScriptFileWin)
	if err := os.MkdirAll(filepath.Dir(unixOutPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(unixOutPath, unixContent, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(windowsOutPath, windowsContent, 0o644); err != nil {
		return err
	}

	ctx.Artifacts.Add(&artifact.Artifact{
		Name: installScriptFileUnix,
		Path: unixOutPath,
		Type: artifact.InstallScript,
		Extra: map[string]any{
			artifact.ExtraID:         installScriptIDUnix,
			installScriptConfigExtra: cfg,
			installScriptKindExtra:   scriptKindUnix,
			installScriptPathExtra:   unixTargetPath,
		},
	})
	ctx.Artifacts.Add(&artifact.Artifact{
		Name: installScriptFileWin,
		Path: windowsOutPath,
		Type: artifact.InstallScript,
		Extra: map[string]any{
			artifact.ExtraID:         installScriptIDWindows,
			installScriptConfigExtra: cfg,
			installScriptKindExtra:   scriptKindWindows,
			installScriptPathExtra:   windowsTargetPath,
		},
	})
	return nil
}

func (Pipe) Publish(ctx *context.Context) error {
	cfg := ctx.Config.InstallScript
	if cfg.Repository.Name == "" && cfg.Repository.Git.URL == "" {
		return nil
	}
	enabled, err := tmpl.New(ctx).Bool(cfg.Enable)
	if err != nil {
		return err
	}
	if cfg.Enable != "" && !enabled {
		return pipe.Skip("install_script.enable evaluates to false")
	}

	cli, err := client.New(ctx)
	if err != nil {
		return err
	}
	return publishAll(ctx, cfg, cli)
}

func publishAll(ctx *context.Context, cfg config.InstallScript, cl client.Client) error {
	msg, err := tmpl.New(ctx).Apply(cfg.CommitMessageTemplate)
	if err != nil {
		return err
	}
	ref, err := client.TemplateRef(tmpl.New(ctx).Apply, cfg.Repository)
	if err != nil {
		return err
	}
	cfg.Repository = ref
	if cfg.Repository.Name == "" && cfg.Repository.Git.URL == "" {
		return errNoRepoName
	}
	author, err := commitauthor.Get(ctx, cfg.CommitAuthor)
	if err != nil {
		return err
	}
	files, err := installScriptFiles(ctx)
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return pipe.Skip("install_script artifacts not found")
	}

	repo := client.RepoFromRef(cfg.Repository)
	if cfg.Repository.Git.URL != "" {
		return client.NewGitUploadClient(repo.Branch).CreateFiles(ctx, author, repo, msg, files)
	}

	cl, err = client.NewIfToken(ctx, cl, cfg.Repository.Token)
	if err != nil {
		return err
	}

	base := client.Repo{
		Name:   cfg.Repository.PullRequest.Base.Name,
		Owner:  cfg.Repository.PullRequest.Base.Owner,
		Branch: cfg.Repository.PullRequest.Base.Branch,
	}
	if fscli, ok := cl.(client.ForkSyncer); ok && cfg.Repository.PullRequest.Enabled {
		if err := fscli.SyncFork(ctx, repo, base); err != nil {
			log.WithError(err).Warn("could not sync fork")
		}
	}

	for _, file := range files {
		if err := cl.CreateFile(ctx, author, repo, file.Content, file.Path, msg); err != nil {
			return err
		}
	}

	if !cfg.Repository.PullRequest.Enabled {
		log.Debug("install_script.pull_request disabled")
		return nil
	}
	log.Info("install_script.pull_request enabled, creating a PR")
	pcl, ok := cl.(client.PullRequestOpener)
	if !ok {
		return errors.New("client does not support pull requests")
	}
	return pcl.OpenPullRequest(ctx, base, repo, msg, cfg.Repository.PullRequest.Draft)
}

func installScriptFiles(ctx *context.Context) ([]client.RepoFile, error) {
	var files []client.RepoFile
	for _, a := range ctx.Artifacts.Filter(artifact.ByType(artifact.InstallScript)).List() {
		content, err := os.ReadFile(a.Path)
		if err != nil {
			return nil, err
		}
		files = append(files, client.RepoFile{
			Path:    artifact.MustExtra[string](*a, installScriptPathExtra),
			Content: content,
		})
	}
	slices.SortFunc(files, func(a, b client.RepoFile) int {
		return cmp.Compare(a.Path, b.Path)
	})
	return files, nil
}

type scriptAsset struct {
	OS              string
	Arch            string
	Kind            string
	Format          string
	NamePattern     string
	URLPattern      string
	BinaryPath      string
	InstallName     string
	SelectionWeight int
}

type scriptTemplateData struct {
	ProjectName           string
	DefaultTag            string
	DefaultVersion        string
	DefaultInstallLinux   string
	DefaultInstallDarwin  string
	DefaultInstallWindows string
	MessageBefore         string
	MessageAfter          string
	GeneratedBy           string
	Assets                []scriptAsset
}

func renderScript(name string, data scriptTemplateData) ([]byte, error) {
	tpl, err := texttemplate.ParseFS(templates, name)
	if err != nil {
		return nil, err
	}
	var out bytes.Buffer
	if err := tpl.Execute(&out, data); err != nil {
		return nil, err
	}
	if !bytes.Contains(out.Bytes(), []byte(generatedMarker)) {
		return nil, errGeneratedMarkerNotPresent
	}
	return out.Bytes(), nil
}

func selectAssets(ctx *context.Context, cfg config.InstallScript, gooses ...string) ([]scriptAsset, error) {
	filters := []artifact.Filter{
		artifact.ByTypes(artifact.UploadableBinary, artifact.UploadableArchive),
		artifact.ByGooses(gooses...),
		artifact.Or(
			artifact.ByGoarch("amd64"),
			artifact.ByGoarch("arm64"),
			artifact.ByGoarch("386"),
			artifact.ByGoarch("arm"),
			artifact.ByGoarch("all"),
		),
	}
	if len(cfg.IDs) > 0 {
		filters = append(filters, artifact.ByIDs(cfg.IDs...))
	}
	candidates := ctx.Artifacts.Filter(artifact.And(filters...)).List()
	if len(candidates) == 0 {
		return nil, errNoSuitableArtifact
	}

	type key struct {
		OS   string
		Arch string
	}
	best := map[key]*artifact.Artifact{}
	for _, a := range candidates {
		if !matchesGOAMD64(a, cfg.Goamd64) {
			continue
		}
		if score(a) >= 99 {
			continue
		}
		k := key{
			OS:   a.Goos,
			Arch: a.Goarch,
		}
		if current, ok := best[k]; !ok || better(a, current) {
			best[k] = a
		}
	}
	if len(best) == 0 {
		return nil, errNoSuitableArtifact
	}

	result := make([]scriptAsset, 0, len(best))
	for k, a := range best {
		u, err := tmpl.New(ctx).WithArtifact(a).Apply(cfg.URLTemplate)
		if err != nil {
			return nil, err
		}
		binaryPath := binaryPathFor(ctx, a)
		result = append(result, scriptAsset{
			OS:              k.OS,
			Arch:            k.Arch,
			Kind:            kind(a),
			Format:          a.Format(),
			NamePattern:     versionPattern(a.Name, ctx),
			URLPattern:      versionPattern(u, ctx),
			BinaryPath:      filepath.ToSlash(binaryPath),
			InstallName:     filepath.Base(binaryPath),
			SelectionWeight: score(a),
		})
	}
	slices.SortFunc(result, func(a, b scriptAsset) int {
		if c := cmp.Compare(a.SelectionWeight, b.SelectionWeight); c != 0 {
			return c
		}
		if c := cmp.Compare(a.OS, b.OS); c != 0 {
			return c
		}
		if c := cmp.Compare(a.Arch, b.Arch); c != 0 {
			return c
		}
		if c := cmp.Compare(a.Format, b.Format); c != 0 {
			return c
		}
		return cmp.Compare(a.NamePattern, b.NamePattern)
	})
	return result, nil
}

func better(a, b *artifact.Artifact) bool {
	if c := cmp.Compare(score(a), score(b)); c != 0 {
		return c < 0
	}
	if c := cmp.Compare(a.Format(), b.Format()); c != 0 {
		return c < 0
	}
	return a.Name < b.Name
}

func matchesGOAMD64(a *artifact.Artifact, cfgGOAMD64 string) bool {
	if a.Goarch != "amd64" {
		return true
	}
	return artifact.ByGoamd64(cfgGOAMD64)(a)
}

func score(a *artifact.Artifact) int {
	if a.Type == artifact.UploadableBinary {
		return 0
	}
	if a.Type == artifact.UploadableArchive {
		switch a.Format() {
		case "tar.gz", "tgz":
			return 1
		default:
			return 2
		}
	}
	return 99
}

func kind(a *artifact.Artifact) string {
	if a.Type == artifact.UploadableBinary {
		return "binary"
	}
	return "archive"
}

func binaryPathFor(ctx *context.Context, a *artifact.Artifact) string {
	switch a.Type {
	case artifact.UploadableBinary:
		bin := artifact.ExtraOr(*a, artifact.ExtraBinary, "")
		if bin != "" {
			return bin
		}
		return a.Name
	case artifact.UploadableArchive:
		bins := artifact.ExtraOr(*a, artifact.ExtraBinaries, []string(nil))
		if len(bins) > 0 {
			return bins[0]
		}
		name := ctx.Config.ProjectName
		if a.Goos == "windows" && !strings.HasSuffix(strings.ToLower(name), ".exe") {
			name += ".exe"
		}
		return name
	default:
		return ctx.Config.ProjectName
	}
}

func versionPattern(in string, ctx *context.Context) string {
	out := in
	if ctx.Git.CurrentTag != "" {
		out = strings.ReplaceAll(out, ctx.Git.CurrentTag, patternTag)
	}
	if ctx.Version != "" {
		out = strings.ReplaceAll(out, ctx.Version, patternVersion)
	}
	return out
}
