package apkbuild

type templateData struct {
	Name            string
	Desc            string
	Homepage        string
	Version         string
	License         string
	ReleasePackages []releasePackage
	Maintainers     []string
	Contributors    []string
	Depends         []string
	MakeDepends     []string
	Arches          []string
	Rel             string
	Package         string
}

type releasePackage struct {
	DownloadURL string
	SHA512      string
	Arch        string
	Format      string
}

// apkbuildTemplate renders an APKBUILD file for Alpine Linux.
// APKBUILD must be pure POSIX sh (not Bash), which is the key difference from AUR's PKGBUILD.
// Reference: https://wiki.alpinelinux.org/wiki/APKBUILD_Reference
const apkbuildTemplate = `# This file was generated by GoReleaser. DO NOT EDIT.
{{- range .Maintainers }}
# Maintainer: {{ . }}
{{- end }}
{{- range .Contributors }}
# Contributor: {{ . }}
{{- end }}

pkgname="{{ .Name }}"
pkgver={{ .Version }}
pkgrel={{ .Rel }}
pkgdesc="{{ .Desc }}"
url="{{ .Homepage }}"
arch="{{ range $i, $a := .Arches }}{{ if $i }} {{ end }}{{ $a }}{{ end }}"
license="{{ .License }}"
{{- with .Depends }}
depends="{{ range $i, $d := . }}{{ if $i }} {{ end }}{{ $d }}{{ end }}"
{{- end }}
{{- with .MakeDepends }}
makedepends="{{ range $i, $d := . }}{{ if $i }} {{ end }}{{ $d }}{{ end }}"
{{- end }}

{{ range .ReleasePackages -}}
source_{{ .Arch }}="{{ $.Name }}-$pkgver-{{ .Arch }}.{{ .Format }}::{{ replaceAll .DownloadURL $.Version "$pkgver" }}"
sha512sums_{{ .Arch }}="{{ .SHA512 }}"
{{ end }}
package() {
{{ fixLines .Package }}
}
`
