package apkbuild

type templateData struct {
	Name            string
	Description     string
	Homepage        string
	Version         string
	License         string
	ReleasePackages []releasePackage
	Maintainers     []string
	Contributors    []string
	Provides        []string
	Depends         []string
	MakeDepends     []string
	Replaces        []string
	Options         []string
	Arches          []string
	Rel             string
	Package         string
}

type releasePackage struct {
	DownloadURL string
	SHA512      string
	Arch        string
	SourceName  string
}

const apkbuildTemplate = `# This file was generated by GoReleaser. DO NOT EDIT.
{{- range .Maintainers }}
# Maintainer: {{ . }}
{{- end }}
{{- range .Contributors }}
# Contributor: {{ . }}
{{- end }}

pkgname={{ shellQuote .Name }}
pkgver={{ shellQuote .Version }}
pkgrel={{ shellQuote .Rel }}
pkgdesc={{ shellQuote .Description }}
url={{ shellQuote .Homepage }}
arch={{ shellJoin .Arches }}
license={{ shellQuote .License }}
{{- with .Provides }}
provides={{ shellJoin . }}
{{- end }}
{{- with .Depends }}
depends={{ shellJoin . }}
{{- end }}
{{- with .MakeDepends }}
makedepends={{ shellJoin . }}
{{- end }}
{{- with .Replaces }}
replaces={{ shellJoin . }}
{{- end }}
{{- with .Options }}
options={{ shellJoin . }} # prebuilt binaries
{{- end }}

case "$CARCH" in
{{- range .ReleasePackages }}
	{{ .Arch }})
		_source={{ shellQuote .SourceName }}
		_url={{ shellQuote .DownloadURL }}
		_sha512={{ shellQuote .SHA512 }}
		;;
{{- end }}
esac
source="$_source::$_url"

package() {
{{ fixLines .Package }}
}

sha512sums="$_sha512  $_source"
`
