package gentoo

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"

	"github.com/caarlos0/log"
	"github.com/goreleaser/goreleaser/v2/internal/artifact"
	"github.com/goreleaser/goreleaser/v2/internal/client"
	"github.com/goreleaser/goreleaser/v2/internal/commitauthor"
	"github.com/goreleaser/goreleaser/v2/internal/extrafiles"
	"github.com/goreleaser/goreleaser/v2/internal/tmpl"
	"github.com/goreleaser/goreleaser/v2/pkg/config"
	"github.com/goreleaser/goreleaser/v2/pkg/context"
)

const ebuildExtra = "GentooConfig"
const ebuildPathExtra = "GentooPath"

const ebuildTemplate = `# This file was generated by GoReleaser. DO NOT EDIT.
EAPI=8

DESCRIPTION="{{ .Description }}"
HOMEPAGE="{{ .Homepage }}"
SRC_URI="
{{- range .Archs }}
{{ .Keyword }}? ( {{ .URI }} -> {{ .File }} )
{{- end }}"

LICENSE="{{ .License }}"
SLOT="0"
KEYWORDS="{{ .Keywords }}"
IUSE="doc"

src_unpack() {
{{- range .Archs }}
  if use {{ .Keyword }}; then
    unpack "${DISTDIR}/{{ .File }}" || die "Can't unpack archive file"
  fi
{{- end }}
}

src_install() {
  exeinto /opt/bin
{{- range .Archs }}
  if use {{ .Keyword }}; then
    newexe "{{ $.Name }}" "{{ $.Name }}" || die "Failed to install binary"
  fi
{{- end }}
  if use doc; then
    dodoc README* || die
  fi
}
`

// Pipe builds and publishes gentoo ebuilds.
type Pipe struct{}

func (Pipe) String() string        { return "gentoo ebuild" }
func (Pipe) ContinueOnError() bool { return true }
func (Pipe) Skip(ctx *context.Context) bool {
	return len(ctx.Config.Gentoos) == 0
}

func (Pipe) Default(ctx *context.Context) error {
	for i := range ctx.Config.Gentoos {
		g := &ctx.Config.Gentoos[i]
		g.CommitAuthor = commitauthor.Default(g.CommitAuthor)
		if !g.Bin {
			return errors.New("gentoo.bin must be true")
		}
		if g.CommitMessageTemplate == "" {
			g.CommitMessageTemplate = "{{ .ProjectName }}: bump to {{ .Tag }}"
		}
		if g.Type == "" {
			g.Type = "bin"
		}
		if len(g.Keywords) == 0 {
			g.Keywords = config.StringArray{"~amd64"}
		}
		if g.License == "" {
			g.License = "MIT"
		}
		if g.Name == "" {
			g.Name = ctx.Config.ProjectName
		}
		if g.Path == "" {
			suffix := ""
			if g.Type == "bin" {
				suffix = "-bin"
			}
			g.Path = filepath.Join("app-misc", g.Name+suffix, fmt.Sprintf("%s%s-{{ .Version }}.ebuild", g.Name, suffix))
		}
	}
	return nil
}

func (Pipe) Run(ctx *context.Context) error {
	cli, err := client.NewReleaseClient(ctx)
	if err != nil {
		return err
	}
	for _, cfg := range ctx.Config.Gentoos {
		if err := doRun(ctx, cfg, cli); err != nil {
			return err
		}
	}
	return nil
}

func doRun(ctx *context.Context, cfg config.Gentoo, cl client.ReleaseURLTemplater) error {
	tp := tmpl.New(ctx)
	if err := tp.ApplyAll(&cfg.Name, &cfg.Path, &cfg.Description, &cfg.Homepage, &cfg.License); err != nil {
		return err
	}

	path := filepath.Join(ctx.Config.Dist, "gentoo", cfg.Path)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	filters := []artifact.Filter{
		artifact.ByGoos("linux"),
		artifact.Or(
			artifact.ByType(artifact.UploadableArchive),
			artifact.ByType(artifact.UploadableBinary),
		),
		artifact.OnlyReplacingUnibins,
	}

	arches := ctx.Artifacts.Filter(artifact.And(filters...)).List()
	if len(arches) == 0 {
		return errors.New("no linux archives found")
	}

	type archData struct {
		Keyword string
		File    string
		URI     string
	}
	var archInfos []archData
	keywordSet := map[string]struct{}{}

	uriTemplate, err := cl.ReleaseURLTemplate(ctx)
	if err != nil {
		return err
	}

	for _, art := range arches {
		url, err := tmpl.New(ctx).WithArtifact(art).Apply(uriTemplate)
		if err != nil {
			return err
		}
		kw := gentooArch(art.Goarch)
		archInfos = append(archInfos, archData{
			Keyword: kw,
			File:    art.Name,
			URI:     url,
		})
		keywordSet["~"+kw] = struct{}{}
	}

	keywords := cfg.Keywords
	if len(keywords) == 0 {
		keywords = make(config.StringArray, 0, len(keywordSet))
		for k := range keywordSet {
			keywords = append(keywords, k)
		}
		slices.Sort(keywords)
	}

	data := struct {
		Name        string
		Description string
		Homepage    string
		License     string
		Keywords    string
		Archs       []archData
	}{
		Name:        cfg.Name,
		Description: cfg.Description,
		Homepage:    cfg.Homepage,
		License:     cfg.License,
		Keywords:    strings.Join(keywords, " "),
		Archs:       archInfos,
	}
	var buf bytes.Buffer
	if err := template.Must(template.New("ebuild").Parse(ebuildTemplate)).Execute(&buf, data); err != nil {
		return err
	}
	content := buf.String()

	log.WithField("ebuild", path).Info("writing")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}

	extraFiles, err := extrafiles.Find(ctx, cfg.Files)
	if err != nil {
		return err
	}
	for name, src := range extraFiles {
		dst := filepath.Join(filepath.Dir(path), name)
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		if err := copyFile(src, dst); err != nil {
			return err
		}
		ctx.Artifacts.Add(&artifact.Artifact{
			Name: name,
			Path: dst,
			Type: artifact.GentooFile,
			Extra: map[string]any{
				ebuildExtra:     cfg,
				ebuildPathExtra: filepath.Join(filepath.Dir(cfg.Path), name),
			},
		})
	}

	ctx.Artifacts.Add(&artifact.Artifact{
		Name: filepath.Base(path),
		Path: path,
		Type: artifact.GentooEbuild,
		Extra: map[string]any{
			ebuildExtra:     cfg,
			ebuildPathExtra: cfg.Path,
		},
	})
	return nil
}

func (Pipe) Publish(ctx *context.Context) error {
	cl, err := client.New(ctx)
	if err != nil {
		return err
	}
	arts := ctx.Artifacts.Filter(artifact.Or(
		artifact.ByType(artifact.GentooEbuild),
		artifact.ByType(artifact.GentooFile),
	)).List()

	type group struct {
		cfg   config.Gentoo
		files []client.RepoFile
	}

	groups := map[string]*group{}

	for _, art := range arts {
		cfg := artifact.MustExtra[config.Gentoo](*art, ebuildExtra)
		if strings.TrimSpace(cfg.SkipUpload) == "true" {
			log.Debug("gentoo.skip_upload is true")
			continue
		}
		key := fmt.Sprintf("%s/%s|%s|%s", cfg.Repository.Owner, cfg.Repository.Name, cfg.Repository.Git.URL, filepath.Dir(cfg.Path))
		g := groups[key]
		if g == nil {
			g = &group{cfg: cfg}
			groups[key] = g
		}
		content, err := os.ReadFile(art.Path)
		if err != nil {
			return err
		}
		g.files = append(g.files, client.RepoFile{
			Content: content,
			Path:    artifact.MustExtra[string](*art, ebuildPathExtra),
		})
	}

	for _, g := range groups {
		msg, err := tmpl.New(ctx).Apply(g.cfg.CommitMessageTemplate)
		if err != nil {
			return err
		}
		author, err := commitauthor.Get(ctx, g.cfg.CommitAuthor)
		if err != nil {
			return err
		}
		repo := client.RepoFromRef(g.cfg.Repository)

		// list existing ebuilds
		if lister, ok := cl.(client.DirectoryLister); ok && g.cfg.KeepVersions > 0 {
			dir := filepath.Dir(g.cfg.Path)
			names, err := lister.ListDir(ctx, repo, dir)
			if err == nil {
				var ebuilds []string
				prefix := g.cfg.Name + "-"
				for _, n := range names {
					if strings.HasPrefix(n, prefix) && strings.HasSuffix(n, ".ebuild") {
						ebuilds = append(ebuilds, n)
					}
				}
				sort.Slice(ebuilds, func(i, j int) bool { return ebuilds[i] > ebuilds[j] })
				for _, n := range ebuilds[g.cfg.KeepVersions-1:] {
					g.files = append(g.files, client.RepoFile{Path: filepath.Join(dir, n), Delete: true})
				}
			}
		}

		if g.cfg.Repository.Git.URL != "" {
			err = client.NewGitUploadClient(repo.Branch).
				CreateFiles(ctx, author, repo, msg, g.files)
		} else if fc, ok := cl.(client.FilesCreator); ok {
			cl, err = client.NewIfToken(ctx, cl, g.cfg.Repository.Token)
			if err != nil {
				return err
			}
			err = fc.CreateFiles(ctx, author, repo, msg, g.files)
		} else {
			for _, f := range g.files {
				if f.Delete {
					if d, ok := cl.(client.FileDeleter); ok {
						if err := d.DeleteFile(ctx, author, repo, f.Path, msg); err != nil {
							return err
						}
					}
					continue
				}
				if err = cl.CreateFile(ctx, author, repo, f.Content, f.Path, msg); err != nil {
					return err
				}
			}
		}

		if !g.cfg.Repository.PullRequest.Enabled {
			continue
		}

		base := client.Repo{
			Name:   g.cfg.Repository.PullRequest.Base.Name,
			Owner:  g.cfg.Repository.PullRequest.Base.Owner,
			Branch: g.cfg.Repository.PullRequest.Base.Branch,
		}
		fscli, ok := cl.(client.ForkSyncer)
		if ok {
			if err := fscli.SyncFork(ctx, repo, base); err != nil {
				log.WithError(err).Warn("could not sync fork")
			}
		}
		pcl, ok := cl.(client.PullRequestOpener)
		if !ok {
			return errors.New("client does not support pull requests")
		}
		if err := pcl.OpenPullRequest(ctx, base, repo, msg, g.cfg.Repository.PullRequest.Draft); err != nil {
			return err
		}
	}
	return nil
}

func gentooArch(goarch string) string {
	switch goarch {
	case "386":
		return "x86"
	default:
		return goarch
	}
}

func copyFile(src, dst string) error {
	in, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, in, 0o644)
}
