// Package gentoo provides a Pipe that builds and publishes gentoo ebuilds.
package gentoo

import (
	"bytes"
	"crypto/sha512"
	"errors"
	"fmt"
	"hash"
	"io"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"

	"github.com/Masterminds/semver/v3"
	"golang.org/x/crypto/blake2b"

	"github.com/caarlos0/log"
	"github.com/goreleaser/goreleaser/v2/internal/artifact"
	"github.com/goreleaser/goreleaser/v2/internal/client"
	"github.com/goreleaser/goreleaser/v2/internal/commitauthor"
	"github.com/goreleaser/goreleaser/v2/internal/extrafiles"
	"github.com/goreleaser/goreleaser/v2/internal/tmpl"
	"github.com/goreleaser/goreleaser/v2/pkg/config"
	"github.com/goreleaser/goreleaser/v2/pkg/context"
)

const (
	ebuildExtra     = "GentooConfig"
	ebuildPathExtra = "GentooPath"
)

const ebuildTemplate = `# This file was generated by GoReleaser. DO NOT EDIT.
EAPI=8

DESCRIPTION="{{ .Description }}"
HOMEPAGE="{{ .Homepage }}"
SRC_URI="
{{- range .Archs }}
{{ .Keyword }}? ( {{ .URI }} -> {{ .File }} )
{{- end }}"

LICENSE="{{ .License }}"
SLOT="0"
KEYWORDS="{{ .Keywords }}"
IUSE="doc"

src_unpack() {
{{- range .Archs }}
  if use {{ .Keyword }}; then
    unpack "${DISTDIR}/{{ .File }}" || die "Can't unpack archive file"
  fi
{{- end }}
}

src_install() {
{{- if .Bindir }}
  exeinto {{ .Bindir }}
{{- end }}
{{- range .Installs }}
  if {{ range $i, $k := .Keywords }}{{ if $i }} || {{ end }}use {{ $k }}{{ end }}; then
    {{- if eq .Source .Target }}
    doexe "{{ .Source }}" || die "Failed to install binary"
    {{- else }}
    newexe "{{ .Source }}" "{{ .Target }}" || die "Failed to install binary"
    {{- end }}
  fi
{{- end }}
  if use doc; then
    dodoc README* || die
  fi
}
`

type installData struct {
	Source   string
	Target   string
	Keywords []string
}

// Pipe builds and publishes gentoo ebuilds.
type Pipe struct{}

func (Pipe) String() string        { return "gentoo ebuild" }
func (Pipe) ContinueOnError() bool { return true }
func (Pipe) Skip(ctx *context.Context) bool {
	return len(ctx.Config.Gentoos) == 0
}

func (Pipe) Default(ctx *context.Context) error {
	for i := range ctx.Config.Gentoos {
		g := &ctx.Config.Gentoos[i]
		g.CommitAuthor = commitauthor.Default(g.CommitAuthor)
		if !g.Bin {
			return errors.New("gentoo.bin must be true")
		}
		if g.CommitMessageTemplate == "" {
			g.CommitMessageTemplate = "{{ .ProjectName }}: bump to {{ .Tag }}"
		}
		if g.Type == "" {
			g.Type = "bin"
		}
		if len(g.Keywords) == 0 {
			g.Keywords = config.StringArray{"~amd64"}
		}
		if g.License == "" {
			return errors.New("gentoo.license is required")
		}
		if g.Name == "" {
			g.Name = ctx.Config.ProjectName
		}
		if g.Path == "" {
			g.Path = defaultPath(g.Name, g.Type)
			log.Warnf("no gentoo category configured for %q; defaulting path to %q", g.Name, filepath.ToSlash(g.Path))
		} else if !hasCategory(g.Path) {
			log.Warnf("gentoo.path %q does not include a category/package path; Gentoo ebuild paths usually look like %q", g.Path, filepath.ToSlash(defaultPath(g.Name, g.Type)))
		}
	}
	return nil
}

func (Pipe) Run(ctx *context.Context) error {
	cli, err := client.NewReleaseClient(ctx)
	if err != nil {
		return err
	}
	for _, cfg := range ctx.Config.Gentoos {
		if err := doRun(ctx, cfg, cli); err != nil {
			return err
		}
	}
	return nil
}

func doRun(ctx *context.Context, cfg config.Gentoo, cl client.ReleaseURLTemplater) error {
	tp := tmpl.New(ctx)
	if err := tp.ApplyAll(&cfg.Name, &cfg.Path, &cfg.Description, &cfg.Homepage, &cfg.License); err != nil {
		return err
	}
	if strings.TrimSpace(cfg.Path) == "" {
		return errors.New("gentoo.path is required and must include the category/package ebuild path")
	}

	path := filepath.Join(ctx.Config.Dist, "gentoo", cfg.Path)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	filters := []artifact.Filter{
		artifact.ByGoos("linux"),
		artifact.Or(
			artifact.ByType(artifact.UploadableArchive),
			artifact.ByType(artifact.UploadableBinary),
		),
		artifact.OnlyReplacingUnibins,
	}

	arches := ctx.Artifacts.Filter(artifact.And(filters...)).List()
	if len(arches) == 0 {
		return errors.New("no linux archives found")
	}

	type archData struct {
		Keyword string
		File    string
		URI     string
	}
	var archInfos []archData
	keywordSet := map[string]struct{}{}

	uriTemplate, err := cl.ReleaseURLTemplate(ctx)
	if err != nil {
		return err
	}

	for _, art := range arches {
		url, err := tmpl.New(ctx).WithArtifact(art).Apply(uriTemplate)
		if err != nil {
			return err
		}
		kw := gentooArch(art.Goarch)
		archInfos = append(archInfos, archData{
			Keyword: kw,
			File:    art.Name,
			URI:     url,
		})
		keywordSet["~"+kw] = struct{}{}
	}

	keywords := cfg.Keywords
	if len(keywords) == 0 {
		keywords = make(config.StringArray, 0, len(keywordSet))
		for k := range keywordSet {
			keywords = append(keywords, k)
		}
		slices.Sort(keywords)
	}

	keywordMap := make(map[string]bool)
	for _, art := range archInfos {
		keywordMap[art.Keyword] = true
	}
	keywordsList := make([]string, 0, len(keywordMap))
	for kw := range keywordMap {
		keywordsList = append(keywordsList, kw)
	}
	slices.Sort(keywordsList)

	installs := []installData{
		{
			Source:   cfg.Name,
			Target:   cfg.Name,
			Keywords: keywordsList,
		},
	}

	data := struct {
		Name        string
		Description string
		Homepage    string
		License     string
		Keywords    string
		Bindir      string
		Archs       []archData
		Installs    []installData
	}{
		Name:        cfg.Name,
		Description: cfg.Description,
		Homepage:    cfg.Homepage,
		License:     cfg.License,
		Keywords:    strings.Join(keywords, " "),
		Bindir:      cfg.Bindir,
		Archs:       archInfos,
		Installs:    installs,
	}
	var buf bytes.Buffer
	if err := template.Must(template.New("ebuild").Parse(ebuildTemplate)).Execute(&buf, data); err != nil {
		return err
	}
	content := buf.String()

	log.WithField("ebuild", path).Info("writing")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}

	extraFiles, err := extrafiles.Find(ctx, cfg.Files)
	if err != nil {
		return err
	}
	for name, src := range extraFiles {
		dst := filepath.Join(filepath.Dir(path), name)
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		if err := copyFile(src, dst); err != nil {
			return err
		}
		ctx.Artifacts.Add(&artifact.Artifact{
			Name: name,
			Path: dst,
			Type: artifact.GentooFile,
			Extra: map[string]any{
				ebuildExtra:     cfg,
				ebuildPathExtra: filepath.Join(filepath.Dir(cfg.Path), name),
			},
		})
	}

	ctx.Artifacts.Add(&artifact.Artifact{
		Name: filepath.Base(path),
		Path: path,
		Type: artifact.GentooEbuild,
		Extra: map[string]any{
			ebuildExtra:     cfg,
			ebuildPathExtra: cfg.Path,
		},
	})
	return nil
}

func (Pipe) Publish(ctx *context.Context) error {
	cl, err := client.New(ctx)
	if err != nil {
		return err
	}
	arts := ctx.Artifacts.Filter(artifact.Or(
		artifact.ByType(artifact.GentooEbuild),
		artifact.ByType(artifact.GentooFile),
	)).List()

	type group struct {
		cfg   config.Gentoo
		files []client.RepoFile
	}

	groups := map[string]*group{}

	for _, art := range arts {
		cfg := artifact.MustExtra[config.Gentoo](*art, ebuildExtra)
		skip, err := tmpl.New(ctx).Apply(cfg.SkipUpload)
		if err != nil {
			return err
		}
		if strings.TrimSpace(skip) == "true" {
			log.Debug("gentoo.skip_upload is true")
			continue
		}
		key := fmt.Sprintf("%s/%s|%s|%s", cfg.Repository.Owner, cfg.Repository.Name, cfg.Repository.Git.URL, filepath.Dir(cfg.Path))
		g := groups[key]
		if g == nil {
			g = &group{cfg: cfg}
			groups[key] = g
		}
		content, err := os.ReadFile(art.Path)
		if err != nil {
			return err
		}
		g.files = append(g.files, client.RepoFile{
			Content: content,
			Path:    filepath.ToSlash(artifact.MustExtra[string](*art, ebuildPathExtra)),
		})
	}

	for _, g := range groups {
		msg, err := tmpl.New(ctx).Apply(g.cfg.CommitMessageTemplate)
		if err != nil {
			return err
		}
		author, err := commitauthor.Get(ctx, g.cfg.CommitAuthor)
		if err != nil {
			return err
		}
		repo := client.RepoFromRef(g.cfg.Repository)

		cl, err = client.NewIfToken(ctx, cl, g.cfg.Repository.Token)
		if err != nil {
			return err
		}

		repoClient := cl
		if g.cfg.Repository.Token != "" {
			var err error
			repoClient, err = client.NewIfToken(ctx, cl, g.cfg.Repository.Token)
			if err != nil {
				return err
			}
		}

		var deletedEbuilds []string
		// list existing ebuilds
		if lister, ok := repoClient.(client.DirectoryLister); ok && g.cfg.KeepVersions > 0 {
			dir := filepath.Dir(g.cfg.Path)
			names, err := lister.ListDir(ctx, repo, dir)
			if err == nil {
				var ebuilds []string
				prefix := g.cfg.Name + "-"
				for _, n := range names {
					if strings.HasPrefix(n, prefix) && strings.HasSuffix(n, ".ebuild") {
						ebuilds = append(ebuilds, n)
					}
				}
				sort.Slice(ebuilds, func(i, j int) bool {
					vIStr := strings.TrimSuffix(strings.TrimPrefix(ebuilds[i], prefix), ".ebuild")
					vJStr := strings.TrimSuffix(strings.TrimPrefix(ebuilds[j], prefix), ".ebuild")
					vI, errI := semver.NewVersion(vIStr)
					vJ, errJ := semver.NewVersion(vJStr)
					if errI == nil && errJ == nil {
						return vI.GreaterThan(vJ)
					}
					return ebuilds[i] > ebuilds[j]
				})
				if len(ebuilds) > g.cfg.KeepVersions-1 {
					for _, n := range ebuilds[g.cfg.KeepVersions-1:] {
						g.files = append(g.files, client.RepoFile{Path: filepath.ToSlash(filepath.Join(dir, n)), Delete: true})
						deletedEbuilds = append(deletedEbuilds, n)
					}
				}
			}
		}

		if err := handleGentooManifestAndMetadata(ctx, g.cfg, repoClient, repo, &g.files, deletedEbuilds); err != nil {
			return err
		}

		if g.cfg.Repository.Git.URL != "" {
			if err := client.NewGitUploadClient(repo.Branch).CreateFiles(ctx, author, repo, msg, g.files); err != nil {
				return err
			}
		} else if fc, ok := repoClient.(client.FilesCreator); ok {
			err = fc.CreateFiles(ctx, author, repo, msg, g.files)
			if err != nil {
				return err
			}
		} else {
			for _, f := range g.files {
				if f.Delete {
					if d, ok := repoClient.(client.FileDeleter); ok {
						if err := d.DeleteFile(ctx, author, repo, f.Path, msg); err != nil {
							return err
						}
					}
					continue
				}
				if err = repoClient.CreateFile(ctx, author, repo, f.Content, f.Path, msg); err != nil {
					return err
				}
			}
		}

		if !g.cfg.Repository.PullRequest.Enabled {
			continue
		}

		base := client.Repo{
			Name:   g.cfg.Repository.PullRequest.Base.Name,
			Owner:  g.cfg.Repository.PullRequest.Base.Owner,
			Branch: g.cfg.Repository.PullRequest.Base.Branch,
		}
		fscli, ok := repoClient.(client.ForkSyncer)
		if ok {
			if err := fscli.SyncFork(ctx, repo, base); err != nil {
				log.WithError(err).Warn("could not sync fork")
			}
		}
		pcl, ok := repoClient.(client.PullRequestOpener)
		if !ok {
			return errors.New("client does not support pull requests")
		}
		if err := pcl.OpenPullRequest(ctx, base, repo, msg, g.cfg.Repository.PullRequest.Draft); err != nil {
			return err
		}
	}
	return nil
}

func gentooArch(goarch string) string {
	switch goarch {
	case "386":
		return "x86"
	default:
		return goarch
	}
}

func defaultPath(name, typ string) string {
	suffix := ""
	if typ == "bin" {
		suffix = "-bin"
	}
	return filepath.Join("app-misc", name+suffix, fmt.Sprintf("%s%s-{{ .Version }}.ebuild", name, suffix))
}

func hasCategory(path string) bool {
	parts := strings.Split(filepath.ToSlash(filepath.Clean(path)), "/")
	return len(parts) >= 3 && parts[0] != "." && parts[0] != "" && parts[1] != "" && parts[2] != ""
}

func copyFile(src, dst string) error {
	in, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, in, 0o644)
}

func handleGentooManifestAndMetadata(ctx *context.Context, cfg config.Gentoo, repoClient client.Client, repo client.Repo, files *[]client.RepoFile, deletedEbuilds []string) error {
	dir := filepath.Dir(cfg.Path)

	if len(cfg.Maintainers) > 0 || cfg.BugsTo != "" || cfg.Homepage != "" {
		var buf bytes.Buffer
		buf.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
		buf.WriteString("<!DOCTYPE pkgmetadata SYSTEM \"https://www.gentoo.org/dtd/metadata.dtd\">\n")
		buf.WriteString("<pkgmetadata>\n")
		for _, m := range cfg.Maintainers {
			buf.WriteString("\t<maintainer type=\"person\">\n")
			if m.Email != "" {
				fmt.Fprintf(&buf, "\t\t<email>%s</email>\n", m.Email)
			}
			if m.Name != "" {
				fmt.Fprintf(&buf, "\t\t<name>%s</name>\n", m.Name)
			}
			buf.WriteString("\t</maintainer>\n")
		}
		if cfg.BugsTo != "" || cfg.Homepage != "" {
			buf.WriteString("\t<upstream>\n")
			if cfg.BugsTo != "" {
				fmt.Fprintf(&buf, "\t\t<bugs-to>%s</bugs-to>\n", cfg.BugsTo)
			}
			if cfg.Homepage != "" {
				fmt.Fprintf(&buf, "\t\t<doc>%s</doc>\n", cfg.Homepage)
			}
			buf.WriteString("\t</upstream>\n")
		}
		buf.WriteString("</pkgmetadata>\n")
		*files = append(*files, client.RepoFile{
			Content: buf.Bytes(),
			Path:    filepath.ToSlash(filepath.Join(dir, "metadata.xml")),
		})
	}

	manifestHashes := []string{"BLAKE2B", "SHA512"}
	if dl, ok := repoClient.(client.FileDownloader); ok {
		if content, err := dl.DownloadFile(ctx, repo, "metadata/layout.conf"); err == nil {
			for lineB := range bytes.SplitSeq(content, []byte{'\n'}) {
				line := string(lineB)
				if strings.HasPrefix(strings.TrimSpace(line), "manifest-hashes") {
					parts := strings.Split(line, "=")
					if len(parts) == 2 {
						manifestHashes = strings.Fields(parts[1])
					}
				}
			}
		}
	}

	var manifestLines []string
	if dl, ok := repoClient.(client.FileDownloader); ok {
		if content, err := dl.DownloadFile(ctx, repo, filepath.ToSlash(filepath.Join(dir, "Manifest"))); err == nil {
			for lineB := range bytes.SplitSeq(content, []byte{'\n'}) {
				line := string(lineB)
				if strings.TrimSpace(line) != "" {
					manifestLines = append(manifestLines, line)
				}
			}
		}
	}

	var deletedVersions []string
	prefix := cfg.Name + "-"
	for _, e := range deletedEbuilds {
		v := strings.TrimSuffix(strings.TrimPrefix(e, prefix), ".ebuild")
		deletedVersions = append(deletedVersions, v)
	}

	var newManifestLines []string
	for _, line := range manifestLines {
		if !strings.HasPrefix(line, "DIST ") {
			newManifestLines = append(newManifestLines, line)
			continue
		}
		fields := strings.Fields(line)
		if len(fields) > 1 {
			filename := fields[1]
			removed := false
			for _, dv := range deletedVersions {
				if idx := strings.Index(filename, dv); idx != -1 {
					isMatch := true
					if idx > 0 && filename[idx-1] != '_' && filename[idx-1] != '-' {
						isMatch = false
					}
					endIdx := idx + len(dv)
					if endIdx < len(filename) {
						next := filename[endIdx]
						if next == '.' {
							if endIdx+1 < len(filename) && filename[endIdx+1] >= '0' && filename[endIdx+1] <= '9' {
								isMatch = false
							}
						} else if next != '_' && next != '-' {
							isMatch = false
						}
					}
					if isMatch {
						removed = true
						break
					}
				}
			}
			if !removed {
				newManifestLines = append(newManifestLines, line)
			}
		} else {
			newManifestLines = append(newManifestLines, line)
		}
	}

	filters := []artifact.Filter{
		artifact.ByGoos("linux"),
		artifact.Or(
			artifact.ByType(artifact.UploadableArchive),
			artifact.ByType(artifact.UploadableBinary),
		),
		artifact.OnlyReplacingUnibins,
	}
	arches := ctx.Artifacts.Filter(artifact.And(filters...)).List()

	for _, art := range arches {
		info, err := os.Stat(art.Path)
		if err != nil {
			return err
		}
		size := info.Size()

		f, err := os.Open(art.Path)
		if err != nil {
			return err
		}
		defer f.Close()

		var writers []io.Writer
		var b2b hash.Hash
		var s512 hash.Hash

		for _, algo := range manifestHashes {
			algo = strings.ToUpper(algo)
			if algo == "BLAKE2B" {
				b2b, _ = blake2b.New512(nil)
				writers = append(writers, b2b)
			} else if algo == "SHA512" {
				s512 = sha512.New()
				writers = append(writers, s512)
			}
		}

		if len(writers) > 0 {
			if _, err := io.Copy(io.MultiWriter(writers...), f); err != nil {
				return err
			}
		}

		line := fmt.Sprintf("DIST %s %d", art.Name, size)
		for _, algo := range manifestHashes {
			algo = strings.ToUpper(algo)
			switch algo {
			case "BLAKE2B":
				if b2b != nil {
					line = fmt.Sprintf("%s BLAKE2B %x", line, b2b.Sum(nil))
				}
			case "SHA512":
				if s512 != nil {
					line = fmt.Sprintf("%s SHA512 %x", line, s512.Sum(nil))
				}
			}
		}
		newManifestLines = append(newManifestLines, line)
	}

	if len(newManifestLines) > 0 {
		slices.Sort(newManifestLines)
		newManifestLines = slices.Compact(newManifestLines)
		*files = append(*files, client.RepoFile{
			Content: []byte(strings.Join(newManifestLines, "\n") + "\n"),
			Path:    filepath.ToSlash(filepath.Join(dir, "Manifest")),
		})
	}
	return nil
}
