name: docs

on:
  push:
    branches:
      - "main"
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: www/go.mod
      - uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3
        with:
          hugo-version: "latest"
          extended: true
      - run: hugo --minify --baseURL="/"
        working-directory: ./www/
      - uses: wjdp/htmltest-action@31be84a95c860a331e0cf9a99f71e3eb39d2f86b # master
        with:
          config: www/htmltest.yml
          path: www/public
