name: docs

on:
  push:
    branches:
      - "main"
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"
      - flake.nix
      - flake.lock
  pull_request:
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"
      - flake.nix
      - flake.lock

permissions:
  contents: read

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: go-task/setup-task@3be4020d41929789a01026e0e427a4321ce0ad44 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task docs:test
