name: generate
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 8 * * *"
permissions: read-all
jobs:
  docs:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2.1.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "install gofumpt"
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: mvdan/gofumpt
          tag: v0.10.0
          extension-matching: disable
          rename-to: gofumpt
          chmod: 0755
      - name: "install jv"
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: santhosh-tekuri/jsonschema
          tag: v6.0.2
      - run: task docs:releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: task docs:generate
      - run: task docs:sponsors
        env:
          GITHUB_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
      - run: task schema:generate
      - run: task schema:validate
      - run: task nix:licenses:generate
      - run: task nodedist:releases:generate
      - name: "sync fork"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: gh repo sync goreleaserbot/goreleaser --branch main --source goreleaser/goreleaser --force || true
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GH_PAT }}
          push-to-fork: goreleaserbot/goreleaser
          branch: auto-update-generated-files
          base: main
          delete-branch: true
          title: "chore: auto-update generated files"
          commit-message: "chore: auto-update generated files"
          author: goreleaserbot <bot@goreleaser.com>
          committer: goreleaserbot <bot@goreleaser.com>
          body: |
            Automated update of generated files.

            Generated by the [generate](https://github.com/goreleaser/goreleaser/actions/workflows/generate.yml) workflow.
  notify:
    runs-on: ubuntu-latest
    needs:
      - docs
    permissions:
      contents: read
      actions: read
    if: ${{ failure() }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@1766a33bf571acdcc0678f00da4fb83aad01ebc7 # v1
        with:
          github-token: ${{ secrets.github_token }}
          title: "generate job failed"
          description: |
            this may cause goreleaser-action to fail, please check:

            https://github.com/goreleaser/goreleaser/actions/workflows/generate.yml
          discord-webhook: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK }}
          username: GoReleaser
          avatar-url: https://avatars.githubusercontent.com/u/24697112?v=4
          include-details: false
