name: gitleaks
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
permissions:
  contents: read
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
        if: ${{ env.GITLEAKS_LICENSE != '' }}
      - uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        if: ${{ env.GITLEAKS_LICENSE != '' }}
        with:
          sarif_file: results.sarif
