name: govulncheck
on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 2 * * *"
permissions:
  contents: read
concurrency:
  group: govulncheck-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          output-format: sarif
          output-file: results.sarif
      - uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: results.sarif
